version: '3.3'
services:
  apiservice:
    build: .
    container_name: cliente_api
    depends_on:
      mysqlsrv:
        condition: service_healthy
    ports:
      - '80:80'
    environment:
      - 'SERVIDOR=${SERVIDOR}'
      - 'USUARIO=${USUARIO}'
      - 'SENHA=${SENHA}'
      - 'PORTA=${PORTA}'
      - 'BANCO=${BANCO}'
  mysqlsrv:
    image: 'mysql:5.7.41-debian'
    container_name: cliente_db
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${SENHA}'
      - 'MYSQL_DATABASE=${BANCO}'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 15
    volumes:
      - '/home/vitorpadovan/data:/var/lib/mysql'