version: '3.3'
services:
  apiservice:
    build: .
    # depends_on:
    #   - mysqlsrv
    ports:
      - '80:80'
  # mysqlsrv:
  #   image: 'mysql:5.7.41-debian'
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     - 'MYSQL_ROOT_PASSWORD=123'
  #     - 'MYSQL_DATABASE=inicial'
  #   # volumes:
  #   #   - '/home/ubuntu/data:/var/lib/postgresql/data'